apiVersion: v1
kind: Secret
metadata:
  name: node3-example-credentials
type: Opaque
data:
  username: ${BMC_NODE3_USERNAME}
  password: ${BMC_NODE3_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: controlplane-3-networkdata
type: Opaque
stringData:
  networkData: |
    interfaces:
    - name: ${CONTROLPLANE3_INTERFACE}
      type: ethernet
      state: up
      mac-address: "${CONTROLPLANE3_MAC}"
      ipv4:
        address:
        - ip:  "${CONTROLPLANE3_IP}"
          prefix-length: "${CONTROLPLANE3_PREFIX}"
        enabled: true
        dhcp: false
    dns-resolver:
      config:
        server:
        - "${DNS_SERVER}"
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: "${CONTROLPLANE3_GATEWAY}"
        next-hop-interface: ${CONTROLPLANE3_INTERFACE}
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: node3-example
  labels:
    cluster-role: control-plane
spec:
  online: true
  bootMACAddress: ${BMC_NODE3_MAC}
  bmc:
    address: ${BMC_NODE3_ADDRESS}
    disableCertificateVerification: true
    credentialsName: node3-example-credentials
  preprovisioningNetworkDataName: controlplane-3-networkdata