---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: single-node-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/18
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: RKE2ControlPlane
    name: single-node-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: single-node-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: single-node-cluster
  namespace: default
spec:
  controlPlaneEndpoint:
    host: ${EDGE_CONTROL_PLANE_IP}
    port: 6443
  noCloudProvider: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: RKE2ControlPlane
metadata:
  name: single-node-cluster
  namespace: default
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3MachineTemplate
    name: single-node-cluster-controlplane
  replicas: 1
  serverConfig:
    cni: calico
    cniMultusEnable: true
  agentConfig:
    format: ignition
    additionalUserData:
      config: |
        variant: fcos
        version: 1.4.0
        passwd:
          users:
           - name: root
             password_hash: "$y$j9T$/t4THH10B7esLiIVBROsE.$G1lyxfy/MoFVOrfXSnWAUq70Tf3mjfZBIe18koGOuXB"
        storage:
          files:
            - path: /var/lib/rancher/rke2/server/manifests/sriov-dp-daemonset.yaml
              overwrite: true
              contents:
                inline: |
                  ---
                  apiVersion: v1
                  kind: ServiceAccount
                  metadata:
                    name: sriov-device-plugin
                    namespace: kube-system
                  ---
                  apiVersion: apps/v1
                  kind: DaemonSet
                  metadata:
                    name: kube-sriov-device-plugin-amd64
                    namespace: kube-system
                    labels:
                      tier: node
                      app: sriovdp
                  spec:
                    selector:
                      matchLabels:
                        name: sriov-device-plugin
                    template:
                      metadata:
                        labels:
                          name: sriov-device-plugin
                          tier: node
                          app: sriovdp
                      spec:
                        hostNetwork: true
                        nodeSelector:
                          kubernetes.io/arch: amd64
                        tolerations:
                        - key: node-role.kubernetes.io/master
                          operator: Exists
                          effect: NoSchedule
                        - key: node-role.kubernetes.io/control-plane
                          operator: Exists
                          effect: NoSchedule
                        serviceAccountName: sriov-device-plugin
                        containers:
                        - name: kube-sriovdp
                          image: rancher/hardened-sriov-network-device-plugin:v3.5.1-build20231009-amd64
                          imagePullPolicy: IfNotPresent
                          args:
                          - --log-dir=sriovdp
                          - --log-level=10
                          securityContext:
                            privileged: true
                          resources:
                            requests:
                              cpu: "250m"
                              memory: "40Mi"
                            limits:
                              cpu: 1
                              memory: "200Mi"
                          volumeMounts:
                          - name: devicesock
                            mountPath: /var/lib/kubelet/device-plugins
                            readOnly: false
                          - name: plugins-registry
                            mountPath: /var/lib/kubelet/plugins_registry
                            readOnly: false
                          - name: log
                            mountPath: /var/log
                          - name: config-volume
                            mountPath: /etc/pcidp
                          - name: device-info
                            mountPath: /var/run/k8s.cni.cncf.io/devinfo/dp
                        volumes:
                          - name: devicesock
                            hostPath:
                              path: /var/lib/kubelet/device-plugins
                          - name: plugins-registry
                            hostPath:
                              path: /var/lib/kubelet/plugins_registry
                          - name: log
                            hostPath:
                              path: /var/log
                          - name: device-info
                            hostPath:
                              path: /var/run/k8s.cni.cncf.io/devinfo/dp
                              type: DirectoryOrCreate
                          - name: config-volume
                            configMap:
                              name: sriovdp-config
                              items:
                              - key: config.json
                                path: config.json
              mode: 0644
              user:
                name: root
              group:
                name: root
            - path: /var/lib/rancher/rke2/server/manifests/configmap-sriov.yaml
              overwrite: true
              contents:
                inline: |
                  apiVersion: v1
                  kind: ConfigMap
                  metadata:
                    name: sriovdp-config
                    namespace: kube-system
                  data:
                    config.json: |
                      {
                          "resourceList": [
                              {
                                  "resourceName": "intel_fec_5g",
                                  "devicetype": "accelerator",
                                  "selectors": {
                                      "vendors": ["${SRIOV_VENDOR}"],
                                      "devices": ["${SRIOV_DEVICE}"]
                                  }
                              },
                              {
                                  "resourceName": "intel_sriov_odu",
                                  "selectors": {
                                      "vendors": ["${SRIOV_VENDOR}"],
                                      "devices": ["${SRIOV_DEVICE}"],
                                      "drivers": ["vfio-pci"],
                                      "pfNames": ["${SRIOV_NET_INTERFACE}"]
                                  }
                              },
                              {
                                  "resourceName": "intel_sriov_oru",
                                  "selectors": {
                                      "vendors": ["${SRIOV_VENDOR}"],
                                      "devices": ["${SRIOV_DEVICE}"],
                                      "drivers": ["vfio-pci"],
                                      "pfNames": ["${SRIOV_NET_INTERFACE}"]
                                  }
                              }
                          ]
                      }
              mode: 0644
              user:
                name: root
              group:
                name: root
        kernel_arguments:
          should_exist:
            - intel_iommu=on
            - intel_pstate=passive
            - processor.max_cstate=1
            - intel_idle.max_cstate=0
            - iommu=pt
            - mce=off
            - hugepagesz=1G hugepages=40
            - hugepagesz=2M hugepages=0
            - default_hugepagesz=1G
            - kthread_cpus=${NON-ISOLATED_CPU_CORES}
            - irqaffinity=${NON-ISOLATED_CPU_CORES}
            - isolcpus=${ISOLATED_CPU_CORES}
            - nohz_full=${ISOLATED_CPU_CORES}
            - rcu_nocbs=${ISOLATED_CPU_CORES}
            - rcu_nocb_poll
            - nosoftlockup 
            - nohz=on
        systemd:
          units:
            - name: rke2-preinstall.service
              enabled: true
              contents: |
                [Unit]
                Description=rke2-preinstall
                Wants=network-online.target
                Before=rke2-install.service
                ConditionPathExists=!/run/cluster-api/bootstrap-success.complete
                [Service]
                Type=oneshot
                User=root
                ExecStartPre=/bin/sh -c "mount -L config-2 /mnt"
                ExecStart=/bin/sh -c "sed -i \"s/BAREMETALHOST_UUID/$(jq -r .uuid /mnt/openstack/latest/meta_data.json)/\" /etc/rancher/rke2/config.yaml"
                ExecStart=/bin/sh -c "echo \"node-name: $(jq -r .name /mnt/openstack/latest/meta_data.json)\" >> /etc/rancher/rke2/config.yaml"
                ExecStartPost=/bin/sh -c "umount /mnt"
                [Install]
                WantedBy=multi-user.target
            - name: cpu-performance.service
              enabled: true
              contents: |
                [Unit]
                Description=CPU perfomance
                Wants=network-online.target
                After=network.target network-online.target
                [Service]
                User=root
                Type=forking
                TimeoutStartSec=900
                ExecStart=/bin/sh -c "cpupower frequency-set -g performance; cpupower frequency-set -u ${CPU_FREQUENCY}; cpupower frequency-set -d ${CPU_FREQUENCY}"
                RemainAfterExit=yes
                KillMode=process
                [Install]
                WantedBy=multi-user.target
            - name: cpu-partitioning.service
              enabled: true
              contents: |
                [Unit]
                Description=cpu-partitioning
                Wants=network-online.target
                After=network.target network-online.target
                [Service]
                Type=oneshot
                User=root
                ExecStart=/bin/sh -c "echo isolated_cores=${ISOLATED_CPU_CORES} > /etc/tuned/cpu-partitioning-variables.conf"
                ExecStartPost=/bin/sh -c "tuned-adm profile cpu-partitioning"
                ExecStartPost=/bin/sh -c "systemctl enable tuned.service"
                [Install]
                WantedBy=multi-user.target
            - name: dpdk-vf-creation.service
              enabled: true
              contents: |
                [Unit]
                Description=DPDK VF creation service
                Wants=network-online.target  rke2-server.target
                After=network.target network-online.target rke2-server.target
                [Service]
                User=root
                Type=forking
                TimeoutStartSec=900
                ExecStart=/bin/sh -c "modprobe vfio-pci enable_sriov=1 disable_idle_d3=1"
                ExecStartPost=/bin/sh -c "dpdk-devbind.py -b vfio-pci ${DPDK_PCI_ADDRESS}"
                ExecStartPost=/bin/sh -c "echo 1 > /sys/bus/pci/devices/${DPDK_PCI_ADDRESS}/sriov_numvfs"
                ExecStartPost=/bin/sh -c "pf_bb_config ACC200 -v 00112233-4455-6677-8899-aabbccddeeff -c /opt/pf-bb-config/acc200_config_vf_5g.cfg; sleep 2"
                RemainAfterExit=yes
                KillMode=process
                [Install]
                WantedBy=multi-user.target
    kubelet:
      extraArgs:
        - provider-id=metal3://BAREMETALHOST_UUID
    version: ${RKE2_VERSION}
    nodeName: "localhost.localdomain"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: single-node-cluster-controlplane
  namespace: default
spec:
  template:
    spec:
      dataTemplate:
        name: single-node-cluster-controlplane-template
      hostSelector:
        matchLabels:
          cluster-role: control-plane
      image:
        checksum: http://imagecache.local:8080/eibimage-slemicro55rt-telco.raw.sha256
        checksumType: sha256
        format: raw
        url: http://imagecache.local:8080/eibimage-slemicro55rt-telco.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: single-node-cluster-controlplane-template
  namespace: default
spec:
  clusterName: single-node-cluster
  metaData:
    objectNames:
      - key: name
        object: machine
      - key: local-hostname
        object: machine
      - key: local_hostname
        object: machine
