kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: longhorn
  namespace: fleet-default
spec:
  repo: https://github.com/suse-edge/misc.git
  branch: main
  paths:
  - fleet-examples/fleets/longhorn/
  targets:
  - name: longhorn-enabled
    clusterSelector:
      matchLabels:
        longhorn: "true"