kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: opni
  namespace: fleet-local
spec:
  repo: https://github.com/suse-edge/misc.git
  branch: main
  paths:
  - fleet-examples/fleets/opni/
  # If the rancher ui plugin operator is not deployed, enable this
  # - fleet-examples/fleets/rancher-ui-plugin-operator